### ISSUE TITLE
Creating a project fails

### ISSUE THREAD

**Issue by theodoorscholte** [blabla1337/skf-flask#419]
Saving a new project results in the following error:
[2018-01-12 13:15:21,599] ERROR in app: Exception on /api/questions_sprint/store [PUT]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/skf-flask/skf/api/questions_sprint/endpoints/question_sprint_store.py", line 28, in put
    result = store_sprint_questions(user_id, data)
  File "/skf-flask/skf/api/questions_sprint/business.py", line 36, in store_sprint_questions
    for results in questions_results:
UnboundLocalError: local variable 'questions_results' referenced before assignment

**Comment by blabla1337** [comment]
I finally have recreated the issue and it only is triggered in Chrome version 62.xxx 
What browser and version are you using?

**Comment by theodoorscholte** [comment]
I had the issue in browsers Chrome, Firefox and Safari. Therefore, I fixed it (see pull request 420).
However, today, I downloaded the latest docker image and I cannot reproduce it anymore....

**Comment by blabla1337** [comment]
Aaah oke weird, we checked and could only reproduce it in the specific chrome version mentioned before. In Safari and firefox it was still working.

Let me try and merge your pull request and then I try again with the 62.xxx version to see

**Comment by theodoorscholte** [comment]
Yes, it works fine in 63.xxx version which I am now using.

**Comment by blabla1337** [comment]
I also tried the new version of SKF online but the issue remains, what I can see is that the memory storage is not working in that versions. We found out because of the JWT token we have in memory storage is not there and thus it generates the above issue. Somebody has an idea why the memory storage is not working for those browser versions? According to the docs is should work...

**Comment by martinmarsicano** [comment]
I created a new environment on an Ubuntu 16 machine and work perfect from scratch. When I try the online demo I get a 500 error when browser makes the PUT request to /api/questions_pre/store, this happens because this request is done before /api/sprint/new and the questions_pre requires a sprintID (which is created in the sprint/new request). It's odd that in my new local environment work good and in the online demo, with the same version, doesn't.

If I create the sprint in the online demo, from the project overview page, the sprint is created properly.

**Comment by blabla1337** [comment]
I still get the error if I use an old version of Chrome, it complains about the JWT header is missing but I do see it in the request. If I do the request from CURL it works perfectly, maybe weird browser querk...

Closing the issue for now because we cannot solve it and with later versions of chrome and safari this bug is not triggered.
